# Generated by Django 4.0.3 on 2022-06-19 05:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entity_address', models.TextField()),
                ('city', models.TextField()),
                ('code', models.BigIntegerField()),
                ('is_headquarter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[['72', 'one year'], ['189', 'three year'], ['262', 'five year']], max_length=150)),
                ('is_tagged', models.BooleanField(default=False)),
                ('is_added_hardcopy', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[['1', 'Instant Bank Payment'], ['2', 'Bank transfer'], ['3', 'Card'], ['4', 'PayPal']], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_number', models.CharField(max_length=250)),
                ('entity_name', models.CharField(max_length=250)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('latest_date_relation', models.DateTimeField()),
                ('address', models.ManyToManyField(blank=True, related_name='parent_company_address', to='app.address')),
            ],
        ),
        migrations.CreateModel(
            name='LEI_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=350)),
                ('applicant_full_name', models.CharField(max_length=450)),
                ('email', models.EmailField(max_length=254)),
                ('entity_name', models.CharField(max_length=250)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('company_number', models.CharField(max_length=250)),
                ('vat_number', models.CharField(max_length=250)),
                ('reason_unprovide', models.TextField()),
                ('total_money', models.BigIntegerField()),
                ('address', models.ManyToManyField(blank=True, related_name='company_address', to='app.address')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_company', to='app.parent_companies')),
            ],
        ),
    ]
