# Generated by Django 4.0.3 on 2022-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_companies',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parent_companies',
            name='latest_date_relation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parent_companies',
            name='to_date',
            field=models.DateField(),
        ),
    ]
