# Generated by Django 4.0.5 on 2022-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lei_user_total_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei_user',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_address', to='app.address'),
        ),
    ]
