# Generated by Django 4.0.5 on 2022-06-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lei_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lei_user',
            old_name='applicant_full_name',
            new_name='applicant_first_name',
        ),
        migrations.AddField(
            model_name='lei_user',
            name='applicant_last_name',
            field=models.CharField(default='ali', max_length=450),
            preserve_default=False,
        ),
    ]
